export enum TYPE_COMMAND {
  CREATESESSION,
  ENDSESSION,
  OPENSHUTTER,
  CLOSESHUTTER,
  WITHDRAW,
  CHECK,
  COUNT,
  PREPAREDEPOSIT,
  DEPOSIT,
  CANCELDEPOSIT,
  THERMALPRINT,
  VTMINFO,
  TURN_IN_LED,
  VIDEOCALL,
  SCANNER,
  LASERPRINT,
  UPSRC_COMMAND,
  FINGERPRINT,
}
export interface ICommand {
  typeCommand: TYPE_COMMAND;
}
